name: jacob
train_dataset: 1
validation_datasets: 2
sample_rate: 12
n_mel_channels: 80
n_window_size: 1024
n_window_stride: 256
n_fft: 1024
lowfreq: 0
highfreq: 8000
window: hann
train_n_segments: 8192
train_max_duration: null
train_min_duration: 0.75
val_n_segments: 66048
val_max_duration: null
val_min_duration: 3
defaults:
- model/generator: v1
- model/train_ds: train_ds
- model/validation_ds: val_ds
model:
  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    nfilt: ${n_mel_channels}
    lowfreq: ${lowfreq}
    highfreq: ${highfreq}
    n_fft: ${n_fft}
    n_window_size: ${n_window_size}
    n_window_stride: ${n_window_stride}
    pad_to: 0
    pad_value: -11.52
    sample_rate: ${sample_rate}
    window: ${window}
    normalize: null
    preemph: null
    dither: 0.0
    frame_splicing: 1
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1.0e-05
    mag_power: 1.0
    use_grads: false
    exact_pad: true
    f: 6
  optim:
    _target_: torch.optim.AdamW
    lr: 0.0002
    betas:
    - 0.8
    - 0.99
    g: 7
  max_steps: 2500000
  l1_loss_factor: 45
  denoise_strength: 0.0025
  train_ds:
    dataset:
      b: 2
    dataloader_params:
      c: 3
  validation_ds:
    dataset:
      d: 4
    dataloader_params:
      e: 5
  a: 1
  generator:
    _target_: nemo.collections.tts.modules.hifigan_modules.Generator
    resblock: 1
    upsample_rates:
    - 8
    - 8
    - 2
    - 2
    upsample_kernel_sizes:
    - 16
    - 16
    - 4
    - 4
    upsample_initial_channel: 512
    resblock_kernel_sizes:
    - 3
    - 7
    - 11
    resblock_dilation_sizes:
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    j: 10
trainer:
  num_nodes: 1
  devices: 1
  accelerator: gpu
  strategy: ddp
  precision: 32
  max_steps: ${model.max_steps}
  accumulate_grad_batches: 1
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 100
  check_val_every_n_epoch: 10
  benchmark: false
  h: 8
exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_loss
    mode: min
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
    entity: null
  resume_if_exists: false
  resume_ignore_no_checkpoint: false
  i: 9
sup_data_path: abc
pitch_fmin: 0
pitch_fmax: 0
pitch_mean: 0
pitch_std: 1
phoneme_dict_path: 3
heteronyms_path: 4
whitelist_path: 5
symbols_embedding_dim: 512
